Hi!

Due to interactive plots and high usuage of ram I deleted the result of the plots so code run smoother.

plots are all of them are checked and most of them used in actual report!

if you want to try the plot simply locate you data run everything before Visualization section and then select the plot what you want to see

Good Luck :)

# input requierments

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/MyDrive"

In [3]:
%cd /content/drive/MyDrive/

/content/drive/MyDrive

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_csv('/content/drive/MyDrive/owid-covid-data.csv')

# Basic EDA

In [6]:
# Display the first few rows of the dataset
pd.set_option('display.max_columns', None)
data.head(15)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
5,AFG,Asia,Afghanistan,2020-01-08,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
6,AFG,Asia,Afghanistan,2020-01-09,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
7,AFG,Asia,Afghanistan,2020-01-10,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
8,AFG,Asia,Afghanistan,2020-01-11,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
9,AFG,Asia,Afghanistan,2020-01-12,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
10,AFG,Asia,Afghanistan,2020-01-13,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
11,AFG,Asia,Afghanistan,2020-01-14,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
12,AFG,Asia,Afghanistan,2020-01-15,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
13,AFG,Asia,Afghanistan,2020-01-16,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
14,AFG,Asia,Afghanistan,2020-01-17,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [7]:
# Check the shape of the dataset (number of rows and columns)
data.shape

(355500, 67)

In [8]:
# Get basic summary statistics
data.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,3.174560e+05,3.458550e+05,3.445960e+05,2.957370e+05,345907.00000,344677.000000,317456.000000,345855.000000,344596.000000,295737.000000,345907.000000,344677.000000,184817.000000,37753.000000,37753.000000,39101.000000,39101.000000,10274.000000,10274.000000,23399.000000,23399.000000,7.938700e+04,7.540300e+04,79387.000000,75403.000000,1.039650e+05,103965.000000,95927.000000,9.434800e+04,7.975500e+04,7.633300e+04,7.301500e+04,4.798000e+04,6.575200e+04,1.826900e+05,79755.000000,76333.000000,73015.000000,47980.000000,182690.000000,1.824540e+05,182454.000000,197651.000000,301837.000000,280674.000000,270883.000000,277860.000000,275104.000000,177317.000000,275755.000000,289786.000000,206871.000000,204057.000000,135082.000000,243453.000000,327105.000000,267274.000000,3.555000e+05,1.221100e+04,12211.000000,12211.000000,12211.000000
mean,6.796974e+06,9.457200e+03,9.491605e+03,8.666838e+04,84.23524,84.532007,103457.466834,143.042496,143.560684,879.848094,0.894258,0.897372,0.911495,675.660133,16.197737,3937.423723,129.662798,337.596652,10.233699,4324.931493,85.556646,2.110457e+07,6.728541e+04,924.254762,3.272466,1.421784e+05,2.826309,0.098163,2.403633e+03,4.548198e+08,2.018963e+08,1.841632e+08,1.178650e+08,7.963363e+05,3.020045e+05,118.814026,52.116669,47.166523,34.483840,1963.598128,1.117299e+05,0.079164,42.714021,402.032723,30.502735,8.698425,5.498437,18970.489132,13.846535,264.296012,8.560962,10.791576,32.909734,50.789928,3.097170,73.711668,0.722433,1.284338e+08,5.312168e+04,9.760347,11.337701,1675.398350
std,4.123893e+07,1.094194e+05,9.374232e+04,4.426444e+05,608.98649,554.835927,152731.556394,1154.807442,595.505275,1105.379761,5.070765,2.751601,0.399925,2172.108367,23.030744,9970.798624,152.842350,526.245893,13.827281,11049.267562,89.172436,8.409869e+07,2.477340e+05,2195.428504,9.033843,1.138215e+06,7.308233,0.115978,3.344366e+04,1.611214e+09,7.064052e+08,6.502917e+08,3.763777e+08,3.299690e+06,1.984431e+06,84.870598,29.762057,29.407684,30.390417,3189.716428,8.071666e+05,0.180181,24.911007,1832.571246,9.081755,6.094205,4.135982,19922.571213,20.090465,120.920132,4.941684,10.780080,13.574019,31.956422,2.548347,7.394913,0.148966,6.606624e+08,1.494480e+05,12.293895,25.166908,1941.471481
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.070000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.137000,15.100000,1.144000,0.526000,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2752.924800
25%,8.285000e+03,0.000000e+00,2.860000e-01,1.280000e+02,0.00000,0.000000,2646.234750,0.000000,0.030000,61.388000,0.000000,0.000000,0.720000,22.000000,2.545000,196.000000,33.762000,20.000000,1.799000,240.000000,25.626500,3.646540e+05,2.244000e+03,43.585500,0.286000,1.486000e+03,0.203000,0.017000,7.100000e+00,1.685810e+06,9.036370e+05,8.527655e+05,4.622260e+05,2.596750e+03,3.160000e+02,39.335000,25.450000,19.100000,4.650000,135.000000,5.600000e+01,0.002000,22.220000,37.728000,22.200000,3.526000,2.085000,3823.194000,0.600000,175.695000,5.350000,1.900000,22.600000,20.859000,1.300000,69.590000,0.602000,4.490020e+05,1.216500e+02,1.430000,-1.590000,73.764453
50%,7.143600e+04,1.000000e+00,2.357100e+01,1.341000e+03,0.00000,0.143000,29017.293000,0.088000,6.143000,384.979000,0.000000,0.009000,0.950000,95.000000,6.891000,783.000000,77.053000,106.000000,5.080000,886.000000,59.036000,2.067330e+06,8.783000e+03,234.141000,0.971000,6.570000e+03,0.851000,0.055000,1.750000e+01,1.199869e+07,6.233673e+06,5.695402e+06,4.537723e+06,2.466600e+04,4.315000e+03,120.150000,61.210000,55.110000,33.510000,697.000000,9.550000e+02,0.017000,42.590000,90.672000,29.700000,6.378000,3.871000,12294.876000,2.500000,245.465000,7.200000,6.300000,33.100000,49.839000,2.500000,75.050000,0.740000,5.882259e+06,5.968999e+03,8.100000,5.720000,1115.956200
75%,7.667340e+05,2.510000e+02,4.821430e+02,1.198800e+04,3.00000,4.857000,136995.770250,33.849000,79.974000,1374.303000,0.169000,0.553000,1.140000,434.000000,19.907000,3046.000000,164.719000,411.750000,13.409500,4002.500000,114.151000,1.024845e+07,3.722900e+04,894.374500,2.914000,3.220500e+04,2.584000,0.138100,5.460000e+01,9.644967e+07,4.476522e+07,4.227189e+07,3.374149e+07,2.067978e+05,3.456900e+04,191.255000,77.430000,73.310000,56.630000,2588.000000,1.055900e+04,0.080000,62.040000,222.873000,38.700000,13.928000,8.643000,27216.445000,21.400000,333.436000,10.790000,19.300000,41.300000,82.502000,4.200000,79.460000,0.829000,2.830170e+07,3.770731e+04,15.380000,16.300000,2746.703700
max,7.718202e+08,8.401960e+06,6.402036e+06,6.978162e+06,27939.00000,14821.857000,737554.506000,228872.025000,37241.781000,6511.885000,603.656000,148.641000,5.870000,28891.000000,180.675000,154497.000000,1526.846000,4838.000000,224.976000,153977.000000,710.788000,9.214000e+09,3.585563e+07,32925.826000,531.062000,1.476998e+07,147.603000,1.000000,1.023632e+06,1.352992e+10,5.629479e+09,5.176653e+09,2.801055e+09,4.967329e+07,4.369164e+07,406.900000,129.070000,126.890000,150.470000,117113.000000,2.107127e+07,11.711000,100.000000,20546.766000,48.200000,27.049000,18.493000,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,100.000000,13.800000,86.750000,0.957000,7.975105e+09,1.289776e+06,76.620000,377.630000,10292.916000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355500 entries, 0 to 355499
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    355500 non-null  object
 1   continent                                   338584 non-null  object
 2   location                                    355500 non-null  object
 3   date                                        355500 non-null  object
 4   total_cases                                 317456 non-null  float64
 5   new_cases                                   345855 non-null  float64
 6   new_cases_smoothed                          344596 non-null  float64
 7   total_deaths                                295737 non-null  float64
 8   new_deaths                                  345907 non-null  float64
 9   new_deaths_smoothed                         344677 non-null  float64
 10  total_cases_per_million                     317456 non-null  float64
 11  new_cases_per_million                       345855 non-null  float64
 12  new_cases_smoothed_per_million              344596 non-null  float64
 13  total_deaths_per_million                    295737 non-null  float64
 14  new_deaths_per_million                      345907 non-null  float64
 15  new_deaths_smoothed_per_million             344677 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37753 non-null   float64
 18  icu_patients_per_million                    37753 non-null   float64
 19  hosp_patients                               39101 non-null   float64
 20  hosp_patients_per_million                   39101 non-null   float64
 21  weekly_icu_admissions                       10274 non-null   float64
 22  weekly_icu_admissions_per_million           10274 non-null   float64
 23  weekly_hosp_admissions                      23399 non-null   float64
 24  weekly_hosp_admissions_per_million          23399 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          79755 non-null   float64
 35  people_vaccinated                           76333 non-null   float64
 36  people_fully_vaccinated                     73015 non-null   float64
 37  total_boosters                              47980 non-null   float64
 38  new_vaccinations                            65752 non-null   float64
 39  new_vaccinations_smoothed                   182690 non-null  float64
 40  total_vaccinations_per_hundred              79755 non-null   float64
 41  people_vaccinated_per_hundred               76333 non-null   float64
 42  people_fully_vaccinated_per_hundred         73015 non-null   float64
 43  total_boosters_per_hundred                  47980 non-null   float64
 44  new_vaccinations_smoothed_per_million       182690 non-null  float64
 45  new_people_vaccinated_smoothed              182454 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  182454 non-null  float64
 47  stringency_index                            197651 non-null  float64
 48  population_density                          301837 non-null  float64
 49  median_age                                  280674 non-null  float64
 50  aged_65_older                               270883 non-null  float64
 51  aged_70_older                               277860 non-null  float64
 52  gdp_per_capita                              275104 non-null  float64
 53  extreme_poverty                             177317 non-null  float64
 54  cardiovasc_death_rate                       275755 non-null  float64
 55  diabetes_prevalence                         289786 non-null  float64
 56  female_smokers                              206871 non-null  float64
 57  male_smokers                                204057 non-null  float64
 58  handwashing_facilities                      135082 non-null  float64
 59  hospital_beds_per_thousand                  243453 non-null  float64
 60  life_expectancy                             327105 non-null  float64
 61  human_development_index                     267274 non-null  float64
 62  population                                  355500 non-null  float64
 63  excess_mortality_cumulative_absolute        12211 non-null   float64
 64  excess_mortality_cumulative                 12211 non-null   float64
 65  excess_mortality                            12211 non-null   float64
 66  excess_mortality_cumulative_per_million     12211 non-null   float64
dtypes: float64(62), object(5)
memory usage: 181.7+ MB

In [10]:
# Get the number of unique values in each column
pd.set_option('display.max_rows', None)
data.nunique()

iso_code                                         255
continent                                          6
location                                         255
date                                            1413
total_cases                                   136080
new_cases                                      27944
new_cases_smoothed                             50130
total_deaths                                   52283
new_deaths                                      4660
new_deaths_smoothed                            11677
total_cases_per_million                       176248
new_cases_per_million                          83037
new_cases_smoothed_per_million                 95947
total_deaths_per_million                      104171
new_deaths_per_million                          9848
new_deaths_smoothed_per_million                10572
reproduction_rate                                380
icu_patients                                    4096
icu_patients_per_million                       13204
hosp_patients                                  10278
hosp_patients_per_million                      25827
weekly_icu_admissions                           1671
weekly_icu_admissions_per_million               4350
weekly_hosp_admissions                          8136
weekly_hosp_admissions_per_million             16917
total_tests                                    78045
new_tests                                      38683
total_tests_per_thousand                       72348
new_tests_per_thousand                         12374
new_tests_smoothed                             44392
new_tests_smoothed_per_thousand                13002
positive_rate                                   5171
tests_per_case                                  7077
tests_units                                        4
total_vaccinations                             78162
people_vaccinated                              73413
people_fully_vaccinated                        70031
total_boosters                                 42930
new_vaccinations                               44475
new_vaccinations_smoothed                      62224
total_vaccinations_per_hundred                 25333
people_vaccinated_per_hundred                   9642
people_fully_vaccinated_per_hundred             9296
total_boosters_per_hundred                      9543
new_vaccinations_smoothed_per_million          12658
new_people_vaccinated_smoothed                 43604
new_people_vaccinated_smoothed_per_hundred      1396
stringency_index                                4820
population_density                               215
median_age                                       142
aged_65_older                                    192
aged_70_older                                    195
gdp_per_capita                                   196
extreme_poverty                                   76
cardiovasc_death_rate                            196
diabetes_prevalence                              150
female_smokers                                   112
male_smokers                                     127
handwashing_facilities                            96
hospital_beds_per_thousand                       102
life_expectancy                                  220
human_development_index                          154
population                                       255
excess_mortality_cumulative_absolute           12012
excess_mortality_cumulative                     4141
excess_mortality                                5301
excess_mortality_cumulative_per_million        12153
dtype: int64

In [11]:
# Check for missing values
data.isnull().sum()

iso_code                                           0
continent                                      16916
location                                           0
date                                               0
total_cases                                    38044
new_cases                                       9645
new_cases_smoothed                             10904
total_deaths                                   59763
new_deaths                                      9593
new_deaths_smoothed                            10823
total_cases_per_million                        38044
new_cases_per_million                           9645
new_cases_smoothed_per_million                 10904
total_deaths_per_million                       59763
new_deaths_per_million                          9593
new_deaths_smoothed_per_million                10823
reproduction_rate                             170683
icu_patients                                  317747
icu_patients_per_million                      317747
hosp_patients                                 316399
hosp_patients_per_million                     316399
weekly_icu_admissions                         345226
weekly_icu_admissions_per_million             345226
weekly_hosp_admissions                        332101
weekly_hosp_admissions_per_million            332101
total_tests                                   276113
new_tests                                     280097
total_tests_per_thousand                      276113
new_tests_per_thousand                        280097
new_tests_smoothed                            251535
new_tests_smoothed_per_thousand               251535
positive_rate                                 259573
tests_per_case                                261152
tests_units                                   248712
total_vaccinations                            275745
people_vaccinated                             279167
people_fully_vaccinated                       282485
total_boosters                                307520
new_vaccinations                              289748
new_vaccinations_smoothed                     172810
total_vaccinations_per_hundred                275745
people_vaccinated_per_hundred                 279167
people_fully_vaccinated_per_hundred           282485
total_boosters_per_hundred                    307520
new_vaccinations_smoothed_per_million         172810
new_people_vaccinated_smoothed                173046
new_people_vaccinated_smoothed_per_hundred    173046
stringency_index                              157849
population_density                             53663
median_age                                     74826
aged_65_older                                  84617
aged_70_older                                  77640
gdp_per_capita                                 80396
extreme_poverty                               178183
cardiovasc_death_rate                          79745
diabetes_prevalence                            65714
female_smokers                                148629
male_smokers                                  151443
handwashing_facilities                        220418
hospital_beds_per_thousand                    112047
life_expectancy                                28395
human_development_index                        88226
population                                         0
excess_mortality_cumulative_absolute          343289
excess_mortality_cumulative                   343289
excess_mortality                              343289
excess_mortality_cumulative_per_million       343289
dtype: int64

# Cleaning Data

In [12]:
columns_to_replace_nan = [
    'total_cases',
    'new_cases',
    'new_cases_smoothed',
    'total_deaths',
    'new_deaths',
    'new_deaths_smoothed',
    'total_cases_per_million',
    'new_cases_per_million',
    'new_cases_smoothed_per_million',
    'total_deaths_per_million',
    'new_deaths_per_million',
    'new_deaths_smoothed_per_million',
    'reproduction_rate',
    'icu_patients',
    'icu_patients_per_million',
    'hosp_patients',
    'hosp_patients_per_million',
    'weekly_icu_admissions',
    'weekly_icu_admissions_per_million',
    'weekly_hosp_admissions',
    'weekly_hosp_admissions_per_million',
    'total_tests',
    'new_tests',
    'total_tests_per_thousand',
    'new_tests_per_thousand',
    'new_tests_smoothed',
    'new_tests_smoothed_per_thousand',
    'positive_rate',
    'tests_per_case',
    'total_vaccinations',
    'people_vaccinated',
    'people_fully_vaccinated',
    'total_boosters',
    'new_vaccinations',
    'new_vaccinations_smoothed',
    'total_vaccinations_per_hundred',
    'people_vaccinated_per_hundred',
    'people_fully_vaccinated_per_hundred',
    'total_boosters_per_hundred',
    'new_vaccinations_smoothed_per_million',
    'new_people_vaccinated_smoothed',
    'new_people_vaccinated_smoothed_per_hundred',
    'excess_mortality_cumulative_absolute',
    'excess_mortality_cumulative',
    'excess_mortality',
    'excess_mortality_cumulative_per_million'
]

# Replace NaN values with 0 for the specified columns
data[columns_to_replace_nan] = data[columns_to_replace_nan].fillna(0)

In [13]:
data.isnull().sum()

iso_code                                           0
continent                                      16916
location                                           0
date                                               0
total_cases                                        0
new_cases                                          0
new_cases_smoothed                                 0
total_deaths                                       0
new_deaths                                         0
new_deaths_smoothed                                0
total_cases_per_million                            0
new_cases_per_million                              0
new_cases_smoothed_per_million                     0
total_deaths_per_million                           0
new_deaths_per_million                             0
new_deaths_smoothed_per_million                    0
reproduction_rate                                  0
icu_patients                                       0
icu_patients_per_million                           0
hosp_patients                                      0
hosp_patients_per_million                          0
weekly_icu_admissions                              0
weekly_icu_admissions_per_million                  0
weekly_hosp_admissions                             0
weekly_hosp_admissions_per_million                 0
total_tests                                        0
new_tests                                          0
total_tests_per_thousand                           0
new_tests_per_thousand                             0
new_tests_smoothed                                 0
new_tests_smoothed_per_thousand                    0
positive_rate                                      0
tests_per_case                                     0
tests_units                                   248712
total_vaccinations                                 0
people_vaccinated                                  0
people_fully_vaccinated                            0
total_boosters                                     0
new_vaccinations                                   0
new_vaccinations_smoothed                          0
total_vaccinations_per_hundred                     0
people_vaccinated_per_hundred                      0
people_fully_vaccinated_per_hundred                0
total_boosters_per_hundred                         0
new_vaccinations_smoothed_per_million              0
new_people_vaccinated_smoothed                     0
new_people_vaccinated_smoothed_per_hundred         0
stringency_index                              157849
population_density                             53663
median_age                                     74826
aged_65_older                                  84617
aged_70_older                                  77640
gdp_per_capita                                 80396
extreme_poverty                               178183
cardiovasc_death_rate                          79745
diabetes_prevalence                            65714
female_smokers                                148629
male_smokers                                  151443
handwashing_facilities                        220418
hospital_beds_per_thousand                    112047
life_expectancy                                28395
human_development_index                        88226
population                                         0
excess_mortality_cumulative_absolute               0
excess_mortality_cumulative                        0
excess_mortality                                   0
excess_mortality_cumulative_per_million            0
dtype: int64

In [14]:
# Display unique values in the 'tests_units' column
unique_tests_units = data['tests_units'].unique()

# Print the unique values
print(unique_tests_units)

[nan 'tests performed' 'units unclear' 'samples tested' 'people tested']

In [15]:
# Replace NaN values in the 'tests_units' column with "no test"
data['tests_units'] = data['tests_units'].fillna("no test")

In [16]:
columns_to_flag_missing = [
    'stringency_index',
    'population_density',
    'median_age',
    'aged_65_older',
    'aged_70_older',
    'gdp_per_capita',
    'extreme_poverty',
    'cardiovasc_death_rate',
    'diabetes_prevalence',
    'female_smokers',
    'male_smokers',
    'handwashing_facilities',
    'hospital_beds_per_thousand',
    'life_expectancy',
    'human_development_index'
]

# Create binary indicator columns for missing values in specified columns
for column in columns_to_flag_missing:
    data[f'{column}_missing'] = data[column].isnull().astype(int)

In [17]:
data.head(15)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million,stringency_index_missing,population_density_missing,median_age_missing,aged_65_older_missing,aged_70_older_missing,gdp_per_capita_missing,extreme_poverty_missing,cardiovasc_death_rate_missing,diabetes_prevalence_missing,female_smokers_missing,male_smokers_missing,handwashing_facilities_missing,hospital_beds_per_thousand_missing,life_expectancy_missing,human_development_index_missing
0,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
1,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
2,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
3,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
4,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
5,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
6,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
7,AFG,Asia,Afghanistan,2020-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
8,AFG,Asia,Afghanistan,2020-01-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
9,AFG,Asia,Afghanistan,2020-01-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
10,AFG,Asia,Afghanistan,2020-01-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
11,AFG,Asia,Afghanistan,2020-01-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
12,AFG,Asia,Afghanistan,2020-01-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
13,AFG,Asia,Afghanistan,2020-01-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0
14,AFG,Asia,Afghanistan,2020-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,41128772.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0

In [18]:
# Filter rows where 'stringency_index_missing' is 1 (indicating missing values)
countries_with_missing_stringency = data.loc[data['aged_65_older_missing'] == 1, 'location'].unique()

# Print the countries with missing values in 'stringency_index'
print("Countries with missing values in 'aged_65_older_missing':")
print(countries_with_missing_stringency)

Countries with missing values in 'aged_65_older_missing':
['Africa' 'American Samoa' 'Andorra' 'Anguilla' 'Asia' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'French Guiana'
 'Gibraltar' 'Greenland' 'Guadeloupe' 'Guernsey' 'High income'
 'Isle of Man' 'Jersey' 'Kosovo' 'Liechtenstein' 'Low income'
 'Lower middle income' 'Marshall Islands' 'Martinique' 'Mayotte' 'Monaco'
 'Montserrat' 'Nauru' 'Niue' 'North America' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palau'
 'Pitcairn' 'Reunion' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'San Marino' 'Scotland'
 'Sint Maarten (Dutch part)' 'South America' 'Syria' 'Taiwan' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Upper middle income' 'Vatican'
 'Wales' 'Wallis and Futuna' 'Western Sahara']

In [19]:
columns_to_check = [
    'stringency_index',
    'population_density',
    'median_age',
    'aged_65_older',
    'aged_70_older',
    'gdp_per_capita',
    'extreme_poverty',
    'cardiovasc_death_rate',
    'diabetes_prevalence',
    'female_smokers',
    'male_smokers',
    'handwashing_facilities',
    'hospital_beds_per_thousand',
    'life_expectancy',
    'human_development_index'
]

for column in columns_to_check:
    # Create a boolean mask for rows where the column's missing indicator is 1
    missing_indicator_column = f'{column}_missing'
    missing_data_mask = data[missing_indicator_column] == 1

    # Extract the unique countries from the filtered rows
    countries_with_missing_data = data.loc[missing_data_mask, 'location'].unique()

    # Print the countries with missing values in the current column
    print(f"Countries with missing values in '{column}':")
    print(countries_with_missing_data)
    print()

Countries with missing values in 'stringency_index':
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland'
 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High income' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia (country)'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']

Countries with missing values in 'population_density':
['Africa' 'Anguilla' 'Asia' 'Bonaire Sint Eustatius and Saba'
 'Cook Islands' 'England' 'Europe' 'European Union' 'Falkland Islands'
 'French Guiana' 'Guadeloupe' 'Guernsey' 'High income' 'Jersey'
 'Low income' 'Lower middle income' 'Martinique' 'Mayotte' 'Montserrat'
 'Niue' 'North America' 'Northern Cyprus' 'Northern Ireland' 'Oceania'
 'Pitcairn' 'Reunion' 'Saint Barthelemy' 'Saint Helena'
 'Saint Pierre and Miquelon' 'Scotland' 'South America' 'South Sudan'
 'Syria' 'Taiwan' 'Tokelau' 'Upper middle income' 'Vatican' 'Wales'
 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'median_age':
['Africa' 'American Samoa' 'Andorra' 'Anguilla' 'Asia' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Gibraltar'
 'Greenland' 'Guernsey' 'High income' 'Isle of Man' 'Jersey' 'Kosovo'
 'Liechtenstein' 'Low income' 'Lower middle income' 'Marshall Islands'
 'Monaco' 'Montserrat' 'Nauru' 'Niue' 'North America' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palau'
 'Pitcairn' 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon' 'San Marino'
 'Scotland' 'Sint Maarten (Dutch part)' 'South America' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Upper middle income' 'Vatican'
 'Wales' 'Wallis and Futuna']

Countries with missing values in 'aged_65_older':
['Africa' 'American Samoa' 'Andorra' 'Anguilla' 'Asia' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'French Guiana'
 'Gibraltar' 'Greenland' 'Guadeloupe' 'Guernsey' 'High income'
 'Isle of Man' 'Jersey' 'Kosovo' 'Liechtenstein' 'Low income'
 'Lower middle income' 'Marshall Islands' 'Martinique' 'Mayotte' 'Monaco'
 'Montserrat' 'Nauru' 'Niue' 'North America' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palau'
 'Pitcairn' 'Reunion' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'San Marino' 'Scotland'
 'Sint Maarten (Dutch part)' 'South America' 'Syria' 'Taiwan' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Upper middle income' 'Vatican'
 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'aged_70_older':
['Africa' 'American Samoa' 'Andorra' 'Anguilla' 'Asia' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Dominica' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Gibraltar'
 'Greenland' 'Guadeloupe' 'Guernsey' 'High income' 'Isle of Man' 'Jersey'
 'Kosovo' 'Liechtenstein' 'Low income' 'Lower middle income'
 'Marshall Islands' 'Monaco' 'Montserrat' 'Nauru' 'Niue' 'North America'
 'Northern Cyprus' 'Northern Ireland' 'Northern Mariana Islands' 'Oceania'
 'Palau' 'Pitcairn' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'San Marino' 'Scotland' 'Serbia'
 'Sint Maarten (Dutch part)' 'South America' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Upper middle income' 'Vatican'
 'Wales' 'Wallis and Futuna']

Countries with missing values in 'gdp_per_capita':
['Africa' 'American Samoa' 'Andorra' 'Anguilla' 'Asia'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands' 'Cook Islands'
 'Cuba' 'Curacao' 'England' 'Europe' 'European Union' 'Faeroe Islands'
 'Falkland Islands' 'French Guiana' 'French Polynesia' 'Gibraltar'
 'Greenland' 'Guadeloupe' 'Guam' 'Guernsey' 'High income' 'Isle of Man'
 'Jersey' 'Liechtenstein' 'Low income' 'Lower middle income' 'Martinique'
 'Mayotte' 'Monaco' 'Montserrat' 'New Caledonia' 'Niue' 'North America'
 'North Korea' 'Northern Cyprus' 'Northern Ireland'
 'Northern Mariana Islands' 'Oceania' 'Pitcairn' 'Reunion'
 'Saint Barthelemy' 'Saint Helena' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Scotland' 'Somalia' 'South America' 'Syria'
 'Taiwan' 'Tokelau' 'Turks and Caicos Islands'
 'United States Virgin Islands' 'Upper middle income' 'Vatican' 'Wales'
 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'extreme_poverty':
['Afghanistan' 'Africa' 'American Samoa' 'Andorra' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Aruba' 'Asia' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Barbados' 'Belarus' 'Belize' 'Bermuda' 'Bonaire Sint Eustatius and Saba'
 'Botswana' 'British Virgin Islands' 'Brunei' 'Cambodia' 'Cape Verde'
 'Cayman Islands' 'Central African Republic' 'Cook Islands' 'Cuba'
 'Curacao' 'Cyprus' 'Czechia' 'Dominica' 'England' 'Equatorial Guinea'
 'Eritrea' 'Eswatini' 'Europe' 'European Union' 'Faeroe Islands'
 'Falkland Islands' 'Finland' 'France' 'French Guiana' 'French Polynesia'
 'Germany' 'Gibraltar' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guernsey' 'Guyana' 'High income' 'Hong Kong' 'Isle of Man' 'Jamaica'
 'Japan' 'Jersey' 'Kiribati' 'Kuwait' 'Lebanon' 'Libya' 'Liechtenstein'
 'Low income' 'Lower middle income' 'Macao' 'Maldives' 'Mali'
 'Marshall Islands' 'Martinique' 'Mayotte' 'Monaco' 'Montserrat' 'Nauru'
 'Netherlands' 'New Caledonia' 'New Zealand' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'Northern Cyprus' 'Northern Ireland'
 'Northern Mariana Islands' 'Oceania' 'Oman' 'Palau' 'Papua New Guinea'
 'Philippines' 'Pitcairn' 'Poland' 'Puerto Rico' 'Qatar' 'Reunion'
 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Scotland' 'Serbia' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovenia'
 'Somalia' 'South America' 'South Sudan' 'Sudan' 'Suriname' 'Switzerland'
 'Syria' 'Taiwan' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Turkmenistan'
 'Turks and Caicos Islands' 'United Arab Emirates'
 'United States Virgin Islands' 'Upper middle income' 'Uzbekistan'
 'Vatican' 'Venezuela' 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'cardiovasc_death_rate':
['Africa' 'Anguilla' 'Aruba' 'Asia' 'Bonaire Sint Eustatius and Saba'
 'British Virgin Islands' 'Cayman Islands' 'Cook Islands' 'Curacao'
 'England' 'Europe' 'European Union' 'Faeroe Islands' 'Falkland Islands'
 'French Guiana' 'French Polynesia' 'Gibraltar' 'Guadeloupe' 'Guernsey'
 'High income' 'Hong Kong' 'Isle of Man' 'Jersey' 'Kosovo' 'Liechtenstein'
 'Low income' 'Lower middle income' 'Macao' 'Martinique' 'Mayotte'
 'Monaco' 'Montserrat' 'Nauru' 'New Caledonia' 'Niue' 'North America'
 'Northern Cyprus' 'Northern Ireland' 'Oceania' 'Palau' 'Pitcairn'
 'Reunion' 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon' 'San Marino'
 'Scotland' 'Sint Maarten (Dutch part)' 'South America' 'Tokelau'
 'Turks and Caicos Islands' 'Tuvalu' 'Upper middle income' 'Vatican'
 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'diabetes_prevalence':
['Africa' 'American Samoa' 'Anguilla' 'Asia'
 'Bonaire Sint Eustatius and Saba' 'Cook Islands' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'French Guiana'
 'Gibraltar' 'Guadeloupe' 'Guernsey' 'High income' 'Isle of Man' 'Jersey'
 'Kosovo' 'Low income' 'Lower middle income' 'Macao' 'Martinique'
 'Mayotte' 'Montserrat' 'Niue' 'North America' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Pitcairn'
 'Reunion' 'Saint Barthelemy' 'Saint Helena' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Scotland' 'Sint Maarten (Dutch part)'
 'South America' 'Syria' 'Taiwan' 'Tokelau' 'Turks and Caicos Islands'
 'Upper middle income' 'Vatican' 'Wales' 'Wallis and Futuna'
 'Western Sahara']

Countries with missing values in 'female_smokers':
['Afghanistan' 'Africa' 'American Samoa' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Aruba' 'Asia' 'Belize' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Burundi' 'Cameroon' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Cook Islands' "Cote d'Ivoire" 'Curacao' 'Democratic Republic of Congo'
 'Dominica' 'England' 'Equatorial Guinea' 'Europe' 'European Union'
 'Faeroe Islands' 'Falkland Islands' 'French Guiana' 'French Polynesia'
 'Gabon' 'Gibraltar' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam' 'Guatemala'
 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'High income' 'Hong Kong'
 'Iraq' 'Isle of Man' 'Jersey' 'Jordan' 'Kosovo' 'Libya' 'Liechtenstein'
 'Low income' 'Lower middle income' 'Macao' 'Madagascar'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mayotte'
 'Micronesia (country)' 'Monaco' 'Montserrat' 'New Caledonia' 'Nicaragua'
 'Niue' 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palestine'
 'Pitcairn' 'Puerto Rico' 'Reunion' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines'
 'San Marino' 'Sao Tome and Principe' 'Scotland'
 'Sint Maarten (Dutch part)' 'Solomon Islands' 'Somalia' 'South America'
 'South Sudan' 'Sudan' 'Syria' 'Taiwan' 'Tajikistan' 'Tokelau'
 'Trinidad and Tobago' 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu'
 'United States Virgin Islands' 'Upper middle income' 'Vatican'
 'Venezuela' 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'male_smokers':
['Afghanistan' 'Africa' 'American Samoa' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Aruba' 'Asia' 'Belize' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Burundi' 'Cameroon' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Cook Islands' "Cote d'Ivoire" 'Curacao' 'Democratic Republic of Congo'
 'Dominica' 'England' 'Equatorial Guinea' 'Europe' 'European Union'
 'Faeroe Islands' 'Falkland Islands' 'French Guiana' 'French Polynesia'
 'Gabon' 'Gibraltar' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam' 'Guatemala'
 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'High income' 'Honduras'
 'Hong Kong' 'Iraq' 'Isle of Man' 'Jersey' 'Jordan' 'Kosovo' 'Libya'
 'Liechtenstein' 'Low income' 'Lower middle income' 'Macao' 'Madagascar'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mayotte'
 'Micronesia (country)' 'Monaco' 'Montserrat' 'New Caledonia' 'Nicaragua'
 'Niue' 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palestine'
 'Peru' 'Pitcairn' 'Puerto Rico' 'Reunion' 'Saint Barthelemy'
 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'San Marino' 'Sao Tome and Principe'
 'Scotland' 'Sint Maarten (Dutch part)' 'Solomon Islands' 'Somalia'
 'South America' 'South Sudan' 'Sudan' 'Syria' 'Taiwan' 'Tajikistan'
 'Tokelau' 'Trinidad and Tobago' 'Turkmenistan' 'Turks and Caicos Islands'
 'Tuvalu' 'United States Virgin Islands' 'Upper middle income' 'Vatican'
 'Venezuela' 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'handwashing_facilities':
['Africa' 'Albania' 'American Samoa' 'Andorra' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Aruba' 'Asia' 'Australia' 'Austria'
 'Bahamas' 'Bahrain' 'Belarus' 'Belgium' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei' 'Bulgaria' 'Canada' 'Cape Verde'
 'Cayman Islands' 'Chile' 'China' 'Cook Islands' 'Croatia' 'Curacao'
 'Cyprus' 'Czechia' 'Denmark' 'Djibouti' 'Dominica' 'England' 'Eritrea'
 'Estonia' 'Europe' 'European Union' 'Faeroe Islands' 'Falkland Islands'
 'Fiji' 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon'
 'Georgia' 'Germany' 'Gibraltar' 'Greece' 'Greenland' 'Grenada'
 'Guadeloupe' 'Guam' 'Guernsey' 'High income' 'Hong Kong' 'Hungary'
 'Iceland' 'Iran' 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Japan'
 'Jersey' 'Jordan' 'Kiribati' 'Kosovo' 'Kuwait' 'Latvia' 'Lebanon' 'Libya'
 'Liechtenstein' 'Lithuania' 'Low income' 'Lower middle income'
 'Luxembourg' 'Macao' 'Malaysia' 'Malta' 'Martinique' 'Mauritius'
 'Mayotte' 'Micronesia (country)' 'Monaco' 'Montenegro' 'Montserrat'
 'Morocco' 'Nauru' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niue' 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Palau'
 'Palestine' 'Panama' 'Papua New Guinea' 'Peru' 'Pitcairn' 'Poland'
 'Portugal' 'Puerto Rico' 'Qatar' 'Reunion' 'Romania' 'Russia'
 'Saint Barthelemy' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Scotland' 'Seychelles' 'Singapore' 'Sint Maarten (Dutch part)'
 'Slovakia' 'Slovenia' 'South America' 'South Korea' 'South Sudan' 'Spain'
 'Sri Lanka' 'Sweden' 'Switzerland' 'Taiwan' 'Tokelau' 'Tonga' 'Turkey'
 'Turks and Caicos Islands' 'Tuvalu' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'United States Virgin Islands'
 'Upper middle income' 'Uruguay' 'Uzbekistan' 'Vatican' 'Venezuela'
 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'hospital_beds_per_thousand':
['Africa' 'American Samoa' 'Andorra' 'Angola' 'Anguilla' 'Aruba' 'Asia'
 'Bermuda' 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Chad' 'Congo' 'Cook Islands' "Cote d'Ivoire" 'Curacao'
 'Democratic Republic of Congo' 'England' 'Europe' 'European Union'
 'Faeroe Islands' 'Falkland Islands' 'French Guiana' 'French Polynesia'
 'Gibraltar' 'Greenland' 'Guadeloupe' 'Guam' 'Guernsey' 'Guinea-Bissau'
 'High income' 'Hong Kong' 'Isle of Man' 'Jersey' 'Kosovo' 'Lesotho'
 'Low income' 'Lower middle income' 'Macao' 'Maldives' 'Martinique'
 'Mauritania' 'Mayotte' 'Micronesia (country)' 'Montserrat' 'Namibia'
 'New Caledonia' 'Nigeria' 'Niue' 'North America' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Oceania' 'Palestine'
 'Papua New Guinea' 'Pitcairn' 'Puerto Rico' 'Reunion' 'Rwanda'
 'Saint Barthelemy' 'Saint Helena' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Samoa' 'Scotland' 'Senegal' 'Sierra Leone'
 'Sint Maarten (Dutch part)' 'South America' 'South Sudan' 'Taiwan'
 'Tokelau' 'Turks and Caicos Islands' 'Tuvalu'
 'United States Virgin Islands' 'Upper middle income' 'Vanuatu' 'Vatican'
 'Wales' 'Wallis and Futuna' 'Western Sahara']

Countries with missing values in 'life_expectancy':
['Africa' 'Asia' 'England' 'Europe' 'European Union' 'Guernsey'
 'High income' 'Jersey' 'Kosovo' 'Low income' 'Lower middle income'
 'North America' 'Northern Cyprus' 'Northern Ireland' 'Oceania' 'Pitcairn'
 'Saint Barthelemy' 'Scotland' 'South America' 'Upper middle income'
 'Wales']

Countries with missing values in 'human_development_index':
['Africa' 'American Samoa' 'Anguilla' 'Aruba' 'Asia' 'Bermuda'
 'Bonaire Sint Eustatius and Saba' 'British Virgin Islands'
 'Cayman Islands' 'Cook Islands' 'Curacao' 'England' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'French Guiana'
 'French Polynesia' 'Gibraltar' 'Greenland' 'Guadeloupe' 'Guam' 'Guernsey'
 'High income' 'Isle of Man' 'Jersey' 'Kosovo' 'Low income'
 'Lower middle income' 'Macao' 'Martinique' 'Mayotte' 'Monaco'
 'Montserrat' 'Nauru' 'New Caledonia' 'Niue' 'North America' 'North Korea'
 'Northern Cyprus' 'Northern Ireland' 'Northern Mariana Islands' 'Oceania'
 'Pitcairn' 'Puerto Rico' 'Reunion' 'Saint Barthelemy' 'Saint Helena'
 'Saint Martin (French part)' 'Saint Pierre and Miquelon' 'San Marino'
 'Scotland' 'Sint Maarten (Dutch part)' 'Somalia' 'South America' 'Taiwan'
 'Tokelau' 'Turks and Caicos Islands' 'Tuvalu'
 'United States Virgin Islands' 'Upper middle income' 'Vatican' 'Wales'
 'Wallis and Futuna' 'Western Sahara']

In [20]:
data['location'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Aruba', 'Asia', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'England', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'European Union',
       'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'High income', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Low income', 'Lower middle income', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (country)', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North America', 'North Korea', 'North Macedonia',
       'Northern Cyprus', 'Northern Ireland', 'Northern Mariana Islands',
       'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Barthelemy',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Pierre and Miquelon',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tokelau',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'United States Virgin Islands',
       'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Vatican', 'Venezuela', 'Vietnam', 'Wales', 'Wallis and Futuna',
       'Western Sahara', 'World', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [21]:
# List of values to be removed from the main data
values_to_remove = ['World', 'Asia', 'Europe', 'North America', 'South America','European Union' , 'High income', 'Lower middle income', 'Low income', 'Upper middle income']

# Filter rows with specified values in the 'location' column
filtered_data = data[data['location'].isin(values_to_remove)]

# Create a separate dataframe with the filtered data
separate_dataframe = filtered_data.copy()

# Remove rows with specified values from the main data
data = data[~data['location'].isin(values_to_remove)]

In [22]:
separate_dataframe.shape

(14102, 82)

In [23]:
data.shape

(341398, 82)

In [24]:
separate_dataframe.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million,stringency_index_missing,population_density_missing,median_age_missing,aged_65_older_missing,aged_70_older_missing,gdp_per_capita_missing,extreme_poverty_missing,cardiovasc_death_rate_missing,diabetes_prevalence_missing,female_smokers_missing,male_smokers_missing,handwashing_facilities_missing,hospital_beds_per_thousand_missing,life_expectancy_missing,human_development_index_missing
16889,OWID_ASI,NaN,Asia,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.721383e+09,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
16890,OWID_ASI,NaN,Asia,2020-01-04,1.0,1.0,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.721383e+09,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
16891,OWID_ASI,NaN,Asia,2020-01-05,1.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.721383e+09,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
16892,OWID_ASI,NaN,Asia,2020-01-06,4.0,3.0,0.0,0.0,0.0,0.0,0.001,0.001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.721383e+09,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
16893,OWID_ASI,NaN,Asia,2020-01-07,4.0,0.0,0.0,0.0,0.0,0.0,0.001,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,no test,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.721383e+09,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

# Advanced DA

In [25]:
columns_to_check = [
    'stringency_index',
    'population_density',
    'median_age',
    'aged_65_older',
    'aged_70_older',
    'gdp_per_capita',
    'extreme_poverty',
    'cardiovasc_death_rate',
    'diabetes_prevalence',
    'female_smokers',
    'male_smokers',
    'handwashing_facilities',
    'hospital_beds_per_thousand',
    'life_expectancy',
    'human_development_index'
]

for column in columns_to_check:
    # Create a boolean mask for rows where the column's missing indicator is 1
    missing_indicator_column = f'{column}_missing'
    missing_data_mask = data[missing_indicator_column] == 1

    # Group by 'location' and sum the missing values for each country
    missing_values_by_country = data.loc[missing_data_mask, ['location', missing_indicator_column]].groupby('location').sum()

    # Print the countries with the number of missing values in the current column
    print(f"Number of missing values in '{column}' by country:")
    print(missing_values_by_country)
    print()

Number of missing values in 'stringency_index' by country:
                                  stringency_index_missing
location
Afghanistan                                            313
Africa                                                1407
Albania                                                313
Algeria                                                313
American Samoa                                        1407
Andorra                                                313
Angola                                                 313
Anguilla                                              1407
Antigua and Barbuda                                   1407
Argentina                                              316
Armenia                                               1407
Aruba                                                  313
Australia                                              313
Austria                                                313
Azerbaijan                                             313
Bahamas                                                313
Bahrain                                                313
Bangladesh                                             313
Barbados                                               313
Belarus                                                313
Belgium                                                313
Belize                                                 313
Benin                                                  313
Bermuda                                                313
Bhutan                                                 313
Bolivia                                                313
Bonaire Sint Eustatius and Saba                       1407
Bosnia and Herzegovina                                 313
Botswana                                               313
Brazil                                                 313
British Virgin Islands                                1407
Brunei                                                 313
Bulgaria                                               317
Burkina Faso                                           313
Burundi                                                313
Cambodia                                               313
Cameroon                                               313
Canada                                                 313
Cape Verde                                             313
Cayman Islands                                        1407
Central African Republic                               313
Chad                                                   313
Chile                                                  313
China                                                  313
Colombia                                               313
Comoros                                               1407
Congo                                                  313
Cook Islands                                          1407
Costa Rica                                             313
Cote d'Ivoire                                          313
Croatia                                                316
Cuba                                                   313
Curacao                                               1407
Cyprus                                                 313
Czechia                                                317
Democratic Republic of Congo                           313
Denmark                                                313
Djibouti                                               313
Dominica                                               313
Dominican Republic                                     313
Ecuador                                                313
Egypt                                                  313
El Salvador                                            313
England                                               1324
Equatorial Guinea                                     1407
Eritrea                                               1388
Estonia                                                313
Eswatini                                               313
Ethiopia                                               313
Faeroe Islands                                         313
Falkland Islands                                      1407
Fiji                                                   313
Finland                                                313
France                                                 313
French Guiana                                         1407
French Polynesia                                      1407
Gabon                                                  313
Gambia                                                 313
Georgia                                                313
Germany                                                313
Ghana                                                  313
Gibraltar                                             1407
Greece                                                 315
Greenland                                              313
Grenada                                               1407
Guadeloupe                                            1407
Guam                                                  1388
Guatemala                                              313
Guernsey                                              1407
Guinea                                                 313
Guinea-Bissau                                         1407
Guyana                                                 313
Haiti                                                  313
Honduras                                               313
Hong Kong                                              243
Hungary                                                313
Iceland                                                313
India                                                  317
Indonesia                                              313
Iran                                                   313
Iraq                                                   313
Ireland                                                313
Isle of Man                                           1407
Israel                                                 313
Italy                                                  316
Jamaica                                                313
Japan                                                  313
Jersey                                                1407
Jordan                                                 313
Kazakhstan                                             313
Kenya                                                  313
Kiribati                                               313
Kosovo                                                 313
Kuwait                                                 313
Kyrgyzstan                                             313
Laos                                                   313
Latvia                                                 313
Lebanon                                                313
Lesotho                                                313
Liberia                                                313
Libya                                                  313
Liechtenstein                                          313
Lithuania                                              314
Luxembourg                                             313
Macao                                                  103
Madagascar                                             313
Malawi                                                 313
Malaysia                                               315
Maldives                                              1407
Mali                                                   313
Malta                                                  313
Marshall Islands                                      1407
Martinique                                            1407
Mauritania                                             313
Mauritius                                              313
Mayotte                                               1407
Mexico                                                 313
Micronesia (country)                                  1407
Moldova                                                313
Monaco                                                 313
Mongolia                                               313
Montenegro                                            1407
Montserrat                                            1407
Morocco                                                313
Mozambique                                             313
Myanmar                                                313
Namibia                                                313
Nauru                                                 1407
Nepal                                                  313
Netherlands                                            315
New Caledonia                                         1407
New Zealand                                            313
Nicaragua                                              313
Niger                                                  313
Nigeria                                                313
Niue                                                  1407
North Korea                                           1407
North Macedonia                                       1407
Northern Cyprus                                        691
Northern Ireland                                      1337
Northern Mariana Islands                              1407
Norway                                                 313
Oceania                                               1407
Oman                                                   313
Pakistan                                               313
Palau                                                 1407
Palestine                                              313
Panama                                                 313
Papua New Guinea                                       313
Paraguay                                               313
Peru                                                   313
Philippines                                            313
Pitcairn                                              1407
Poland                                                 314
Portugal                                               313
Puerto Rico                                           1388
Qatar                                                  313
Reunion                                               1407
Romania                                                313
Russia                                                 313
Rwanda                                                 313
Saint Barthelemy                                      1407
Saint Helena                                          1407
Saint Kitts and Nevis                                 1407
Saint Lucia                                           1407
Saint Martin (French part)                            1407
Saint Pierre and Miquelon                             1407
Saint Vincent and the Grenadines                      1407
Samoa                                                 1407
San Marino                                             313
Sao Tome and Principe                                 1407
Saudi Arabia                                           313
Scotland                                              1305
Senegal                                                313
Serbia                                                 313
Seychelles                                             313
Sierra Leone                                           313
Singapore                                              313
Sint Maarten (Dutch part)                             1407
Slovakia                                               313
Slovenia                                               313
Solomon Islands                                        313
Somalia                                                313
South Africa                                           313
South Korea                                            313
South Sudan                                            313
Spain                                                  313
Sri Lanka                                              313
Sudan                                                  313
Suriname                                               313
Sweden                                                 314
Switzerland                                            313
Syria                                                  313
Taiwan                                                 267
Tajikistan                                             313
Tanzania                                               313
Thailand                                               313
Timor                                                  313
Togo                                                   313
Tokelau                                               1407
Tonga                                                  313
Trinidad and Tobago                                    313
Tunisia                                                313
Turkey                                                 313
Turkmenistan                                           313
Turks and Caicos Islands                              1407
Tuvalu                                                1407
Uganda                                                 313
Ukraine                                                313
United Arab Emirates                                   313
United Kingdom                                         313
United States                                          313
United States Virgin Islands                          1388
Uruguay                                                317
Uzbekistan                                             313
Vanuatu                                                313
Vatican                                               1407
Venezuela                                              313
Vietnam                                                313
Wales                                                 1198
Wallis and Futuna                                     1407
Western Sahara                                           1
Yemen                                                  313
Zambia                                                 313
Zimbabwe                                               313

Number of missing values in 'population_density' by country:
                                 population_density_missing
location
Africa                                                 1407
Anguilla                                               1407
Bonaire Sint Eustatius and Saba                        1407
Cook Islands                                           1407
England                                                1324
Falkland Islands                                       1407
French Guiana                                          1407
Guadeloupe                                             1407
Guernsey                                               1407
Jersey                                                 1407
Martinique                                             1407
Mayotte                                                1407
Montserrat                                             1407
Niue                                                   1407
Northern Cyprus                                         691
Northern Ireland                                       1337
Oceania                                                1407
Pitcairn                                               1407
Reunion                                                1407
Saint Barthelemy                                       1407
Saint Helena                                           1407
Saint Pierre and Miquelon                              1407
Scotland                                               1305
South Sudan                                            1407
Syria                                                  1407
Taiwan                                                 1348
Tokelau                                                1407
Vatican                                                1407
Wales                                                  1198
Wallis and Futuna                                      1407
Western Sahara                                            1

Number of missing values in 'median_age' by country:
                                 median_age_missing
location
Africa                                         1407
American Samoa                                 1407
Andorra                                        1407
Anguilla                                       1407
Bermuda                                        1407
Bonaire Sint Eustatius and Saba                1407
British Virgin Islands                         1407
Cayman Islands                                 1407
Cook Islands                                   1407
Dominica                                       1407
England                                        1324
Faeroe Islands                                 1407
Falkland Islands                               1407
Gibraltar                                      1407
Greenland                                      1407
Guernsey                                       1407
Isle of Man                                    1407
Jersey                                         1407
Kosovo                                         1407
Liechtenstein                                  1407
Marshall Islands                               1407
Monaco                                         1407
Montserrat                                     1407
Nauru                                          1407
Niue                                           1407
Northern Cyprus                                 691
Northern Ireland                               1337
Northern Mariana Islands                       1407
Oceania                                        1407
Palau                                          1407
Pitcairn                                       1407
Saint Barthelemy                               1407
Saint Helena                                   1407
Saint Kitts and Nevis                          1407
Saint Martin (French part)                     1407
Saint Pierre and Miquelon                      1407
San Marino                                     1407
Scotland                                       1305
Sint Maarten (Dutch part)                      1407
Tokelau                                        1407
Turks and Caicos Islands                       1407
Tuvalu                                         1407
Vatican                                        1407
Wales                                          1198
Wallis and Futuna                              1407

Number of missing values in 'aged_65_older' by country:
                                 aged_65_older_missing
location
Africa                                            1407
American Samoa                                    1407
Andorra                                           1407
Anguilla                                          1407
Bermuda                                           1407
Bonaire Sint Eustatius and Saba                   1407
British Virgin Islands                            1407
Cayman Islands                                    1407
Cook Islands                                      1407
Dominica                                          1407
England                                           1324
Faeroe Islands                                    1407
Falkland Islands                                  1407
French Guiana                                     1407
Gibraltar                                         1407

In [26]:
data['total_cases'].max()

103436829.0

In [27]:
#Find the index of the row with the maximum value in the 'total_cases' column
max_row_index = data['total_cases'].idxmax()

# Use the index to locate the entire row in the dataframe
max_row = data.loc[max_row_index]

# Display the row with the maximum value in the 'total_cases' column
max_row

iso_code                                                USA
continent                                     North America
location                                      United States
date                                             2023-05-14
total_cases                                     103436829.0
new_cases                                           93260.0
new_cases_smoothed                                13322.857
total_deaths                                      1127152.0
new_deaths                                           1943.0
new_deaths_smoothed                                 277.571
total_cases_per_million                           305763.91
new_cases_per_million                               275.681
new_cases_smoothed_per_million                       39.383
total_deaths_per_million                           3331.912
new_deaths_per_million                                5.744
new_deaths_smoothed_per_million                       0.821
reproduction_rate                                       0.0
icu_patients                                          987.0
icu_patients_per_million                              2.918
hosp_patients                                        7761.0
hosp_patients_per_million                            22.942
weekly_icu_admissions                                   0.0
weekly_icu_admissions_per_million                       0.0
weekly_hosp_admissions                               9188.0
weekly_hosp_admissions_per_million                    27.16
total_tests                                             0.0
new_tests                                               0.0
total_tests_per_thousand                                0.0
new_tests_per_thousand                                  0.0
new_tests_smoothed                                      0.0
new_tests_smoothed_per_thousand                         0.0
positive_rate                                           0.0
tests_per_case                                          0.0
tests_units                                         no test
total_vaccinations                                      0.0
people_vaccinated                                       0.0
people_fully_vaccinated                                 0.0
total_boosters                                          0.0
new_vaccinations                                        0.0
new_vaccinations_smoothed                               0.0
total_vaccinations_per_hundred                          0.0
people_vaccinated_per_hundred                           0.0
people_fully_vaccinated_per_hundred                     0.0
total_boosters_per_hundred                              0.0
new_vaccinations_smoothed_per_million                   0.0
new_people_vaccinated_smoothed                          0.0
new_people_vaccinated_smoothed_per_hundred              0.0
stringency_index                                        NaN
population_density                                   35.608
median_age                                             38.3
aged_65_older                                        15.413
aged_70_older                                         9.732
gdp_per_capita                                    54225.446
extreme_poverty                                         1.2
cardiovasc_death_rate                               151.089
diabetes_prevalence                                   10.79
female_smokers                                         19.1
male_smokers                                           24.6
handwashing_facilities                                  NaN
hospital_beds_per_thousand                             2.77
life_expectancy                                       78.86
human_development_index                               0.926
population                                      338289856.0
excess_mortality_cumulative_absolute              1255025.6
excess_mortality_cumulative                           12.47
excess_mortality                                       1.91
excess_mortality_cumulative_per_million            3691.289
stringency_index_missing                                  1
population_density_missing                                0
median_age_missing                                        0
aged_65_older_missing                                     0
aged_70_older_missing                                     0
gdp_per_capita_missing                                    0
extreme_poverty_missing                                   0
cardiovasc_death_rate_missing                             0
diabetes_prevalence_missing                               0
female_smokers_missing                                    0
male_smokers_missing                                      0
handwashing_facilities_missing                            1
hospital_beds_per_thousand_missing                        0
life_expectancy_missing                                   0
human_development_index_missing                           0
Name: 335818, dtype: object

In [28]:
separate_dataframe['total_cases'].max()

771820173.0

In [29]:
separate_dataframe['total_deaths'].max()

6978162.0

In [30]:
data['total_deaths'].max()

1138309.0

In [31]:
# Find the index of the row with the maximum value in the 'total_cases' column
max_row_index = data['total_deaths'].idxmax()

# Use the index to locate the entire row in the dataframe
max_row = data.loc[max_row_index]

# Display the row with the maximum value in the 'total_cases' column
max_row

iso_code                                                USA
continent                                     North America
location                                      United States
date                                             2023-10-10
total_cases                                     103436829.0
new_cases                                               0.0
new_cases_smoothed                                      0.0
total_deaths                                      1138309.0
new_deaths                                              0.0
new_deaths_smoothed                                     0.0
total_cases_per_million                           305763.91
new_cases_per_million                                   0.0
new_cases_smoothed_per_million                          0.0
total_deaths_per_million                           3364.893
new_deaths_per_million                                  0.0
new_deaths_smoothed_per_million                         0.0
reproduction_rate                                       0.0
icu_patients                                         1781.0
icu_patients_per_million                              5.265
hosp_patients                                       14368.0
hosp_patients_per_million                            42.472
weekly_icu_admissions                                   0.0
weekly_icu_admissions_per_million                       0.0
weekly_hosp_admissions                              16909.0
weekly_hosp_admissions_per_million                   49.984
total_tests                                             0.0
new_tests                                               0.0
total_tests_per_thousand                                0.0
new_tests_per_thousand                                  0.0
new_tests_smoothed                                      0.0
new_tests_smoothed_per_thousand                         0.0
positive_rate                                           0.0
tests_per_case                                          0.0
tests_units                                         no test
total_vaccinations                                      0.0
people_vaccinated                                       0.0
people_fully_vaccinated                                 0.0
total_boosters                                          0.0
new_vaccinations                                        0.0
new_vaccinations_smoothed                               0.0
total_vaccinations_per_hundred                          0.0
people_vaccinated_per_hundred                           0.0
people_fully_vaccinated_per_hundred                     0.0
total_boosters_per_hundred                              0.0
new_vaccinations_smoothed_per_million                   0.0
new_people_vaccinated_smoothed                          0.0
new_people_vaccinated_smoothed_per_hundred              0.0
stringency_index                                        NaN
population_density                                   35.608
median_age                                             38.3
aged_65_older                                        15.413
aged_70_older                                         9.732
gdp_per_capita                                    54225.446
extreme_poverty                                         1.2
cardiovasc_death_rate                               151.089
diabetes_prevalence                                   10.79
female_smokers                                         19.1
male_smokers                                           24.6
handwashing_facilities                                  NaN
hospital_beds_per_thousand                             2.77
life_expectancy                                       78.86
human_development_index                               0.926
population                                      338289856.0
excess_mortality_cumulative_absolute                    0.0
excess_mortality_cumulative                             0.0
excess_mortality                                        0.0
excess_mortality_cumulative_per_million                 0.0
stringency_index_missing                                  1
population_density_missing                                0
median_age_missing                                        0
aged_65_older_missing                                     0
aged_70_older_missing                                     0
gdp_per_capita_missing                                    0
extreme_poverty_missing                                   0
cardiovasc_death_rate_missing                             0
diabetes_prevalence_missing                               0
female_smokers_missing                                    0
male_smokers_missing                                      0
handwashing_facilities_missing                            1
hospital_beds_per_thousand_missing                        0
life_expectancy_missing                                   0
human_development_index_missing                           0
Name: 335967, dtype: object

In [32]:
data['new_deaths'].max()

11447.0

In [33]:
# Find the index of the row with the maximum value in the 'total_cases' column
max_row_index = data['new_deaths'].idxmax()

# Use the index to locate the entire row in the dataframe
max_row = data.loc[max_row_index]

# Display the row with the maximum value in the 'total_cases' column
max_row

iso_code                                                  CHL
continent                                       South America
location                                                Chile
date                                               2022-03-22
total_cases                                         3401145.0
new_cases                                              8167.0
new_cases_smoothed                                  12557.571
total_deaths                                          55965.0
new_deaths                                            11447.0
new_deaths_smoothed                                  1708.571
total_cases_per_million                            173494.736
new_cases_per_million                                 416.604
new_cases_smoothed_per_million                         640.57
total_deaths_per_million                             2854.813
new_deaths_per_million                                583.919
new_deaths_smoothed_per_million                        87.155
reproduction_rate                                        0.69
icu_patients                                            769.0
icu_patients_per_million                               39.227
hosp_patients                                             0.0
hosp_patients_per_million                                 0.0
weekly_icu_admissions                                   217.0
weekly_icu_admissions_per_million                      11.069
weekly_hosp_admissions                                 1099.0
weekly_hosp_admissions_per_million                     56.061
total_tests                                        34572962.0
new_tests                                             42589.0
total_tests_per_thousand                             1773.592
new_tests_per_thousand                                  2.185
new_tests_smoothed                                    86227.0
new_tests_smoothed_per_thousand                         4.423
positive_rate                                          0.1379
tests_per_case                                            7.3
tests_units                                   tests performed
total_vaccinations                                 50336745.0
people_vaccinated                                  17864357.0
people_fully_vaccinated                            17353943.0
total_boosters                                     15692975.0
new_vaccinations                                      81130.0
new_vaccinations_smoothed                             59740.0
total_vaccinations_per_hundred                         256.77
people_vaccinated_per_hundred                           91.13
people_fully_vaccinated_per_hundred                     88.52
total_boosters_per_hundred                              80.05
new_vaccinations_smoothed_per_million                  3047.0
new_people_vaccinated_smoothed                         1914.0
new_people_vaccinated_smoothed_per_hundred               0.01
stringency_index                                        28.84
population_density                                     24.282
median_age                                               35.4
aged_65_older                                          11.087
aged_70_older                                           6.938
gdp_per_capita                                      22767.037
extreme_poverty                                           1.3
cardiovasc_death_rate                                 127.993
diabetes_prevalence                                      8.46
female_smokers                                           34.2
male_smokers                                             41.5
handwashing_facilities                                    NaN
hospital_beds_per_thousand                               2.11
life_expectancy                                         80.18
human_development_index                                 0.851
population                                         19603736.0
excess_mortality_cumulative_absolute                      0.0
excess_mortality_cumulative                               0.0
excess_mortality                                          0.0
excess_mortality_cumulative_per_million                   0.0
stringency_index_missing                                    0
population_density_missing                                  0
median_age_missing                                          0
aged_65_older_missing                                       0
aged_70_older_missing                                       0
gdp_per_capita_missing                                      0
extreme_poverty_missing                                     0
cardiovasc_death_rate_missing                               0
diabetes_prevalence_missing                                 0
female_smokers_missing                                      0
male_smokers_missing                                        0
handwashing_facilities_missing                              1
hospital_beds_per_thousand_missing                          0
life_expectancy_missing                                     0
human_development_index_missing                             0
Name: 61323, dtype: object

In [34]:
separate_dataframe['new_deaths'].max()

27939.0

In [35]:
# Find the index of the row with the maximum value in the 'total_cases' column
max_row_index = separate_dataframe['new_deaths'].idxmax()

# Use the index to locate the entire row in the dataframe
max_row = separate_dataframe.loc[max_row_index]

# Display the row with the maximum value in the 'total_cases' column
max_row

iso_code                                          OWID_WRL
continent                                              NaN
location                                             World
date                                            2021-01-24
total_cases                                     98650758.0
new_cases                                        1155153.0
new_cases_smoothed                              603874.857
total_deaths                                     2280859.0
new_deaths                                         27939.0
new_deaths_smoothed                                14817.0
total_cases_per_million                          12369.838
new_cases_per_million                              144.845
new_cases_smoothed_per_million                       75.72
total_deaths_per_million                           285.997
new_deaths_per_million                               3.503
new_deaths_smoothed_per_million                      1.858
reproduction_rate                                     0.91
icu_patients                                           0.0
icu_patients_per_million                               0.0
hosp_patients                                          0.0
hosp_patients_per_million                              0.0
weekly_icu_admissions                                  0.0
weekly_icu_admissions_per_million                      0.0
weekly_hosp_admissions                                 0.0
weekly_hosp_admissions_per_million                     0.0
total_tests                                            0.0
new_tests                                              0.0
total_tests_per_thousand                               0.0
new_tests_per_thousand                                 0.0
new_tests_smoothed                                     0.0
new_tests_smoothed_per_thousand                        0.0
positive_rate                                          0.0
tests_per_case                                         0.0
tests_units                                        no test
total_vaccinations                              73241304.0
people_vaccinated                               47673358.0
people_fully_vaccinated                          6971271.0
total_boosters                                       536.0
new_vaccinations                                 2764585.0
new_vaccinations_smoothed                        4019237.0
total_vaccinations_per_hundred                        0.92
people_vaccinated_per_hundred                          0.6
people_fully_vaccinated_per_hundred                   0.09
total_boosters_per_hundred                             0.0
new_vaccinations_smoothed_per_million                504.0
new_people_vaccinated_smoothed                   2316107.0
new_people_vaccinated_smoothed_per_hundred           0.029
stringency_index                                       NaN
population_density                                  58.045
median_age                                            30.9
aged_65_older                                        8.696
aged_70_older                                        5.355
gdp_per_capita                                   15469.207
extreme_poverty                                       10.0
cardiovasc_death_rate                               233.07
diabetes_prevalence                                   8.51
female_smokers                                       6.434
male_smokers                                        34.635
handwashing_facilities                               60.13
hospital_beds_per_thousand                           2.705
life_expectancy                                      72.58
human_development_index                              0.737
population                                    7975105024.0
excess_mortality_cumulative_absolute                   0.0
excess_mortality_cumulative                            0.0
excess_mortality                                       0.0
excess_mortality_cumulative_per_million                0.0
stringency_index_missing                                 1
population_density_missing                               0
median_age_missing                                       0
aged_65_older_missing                                    0
aged_70_older_missing                                    0
gdp_per_capita_missing                                   0
extreme_poverty_missing                                  0
cardiovasc_death_rate_missing                            0
diabetes_prevalence_missing                              0
female_smokers_missing                                   0
male_smokers_missing                                     0
handwashing_facilities_missing                           0
hospital_beds_per_thousand_missing                       0
life_expectancy_missing                                  0
human_development_index_missing                          0
Name: 350255, dtype: object

# Visualization

In [ ]:
import plotly.express as px

In [ ]:
# Line plot for total cases over time
fig = px.line(data, x='date', y='total_cases', color='location', title='Total Cases Over Time')
fig.update_xaxes(title_text='Date')
fig.update_yaxes(title_text='Total Cases')
fig.show()

In [ ]:
# Line plot for total deaths over time
fig = px.line(data, x='date', y='total_deaths', color='location', title='Total Deaths Over Time')
fig.update_xaxes(title_text='Date')
fig.update_yaxes(title_text='Total Deaths')
fig.show()

In [ ]:
# Line plot for total vaccinations over time
fig = px.line(data, x='date', y='total_vaccinations', color='location', title='Total Vaccinations Over Time')
fig.update_xaxes(title_text='Date')
fig.update_yaxes(title_text='Total Vaccinations')
fig.show()

In [ ]:
# Scatter plot for total cases vs. total deaths
fig = px.scatter(data, x='total_cases', y='total_deaths', color='location', title='Total Cases vs. Total Deaths')
fig.update_xaxes(title_text='Total Cases')
fig.update_yaxes(title_text='Total Deaths')
fig.show()

In [ ]:
!pip install folium

In [ ]:
import folium
from folium.plugins import MarkerCluster

# Find the row with the maximum total cases
max_total_cases_row = data.loc[data['total_cases'].idxmax()]

# Create a Folium map centered around the location with maximum total cases
map_center = [max_total_cases_row['total_cases'], max_total_cases_row['total_cases']]
my_map = folium.Map(location=map_center, zoom_start=2)

# Add markers for each location with total cases
marker_cluster = MarkerCluster().add_to(my_map)

for index, row in data.iterrows():
    popup_text = f"{row['location']} - Total Cases: {row['total_cases']}"
    marker_color = 'red' if row['location'] == max_total_cases_row['location'] else 'blue'

    folium.Marker([row['total_cases'], row['total_cases']],
                  popup=popup_text,
                  icon=folium.Icon(color=marker_color)
                 ).add_to(marker_cluster)

# Save the map as an HTML file or display it
my_map.save('covid_total_cases_map_max.html')

In [ ]:
import plotly.express as px

fig = px.scatter_geo(data,
                     locations="location",
                     locationmode="country names",
                     color="total_cases",
                     size="total_cases",
                     projection="natural earth",
                     title="Total COVID-19 Cases by Location",
                     hover_name="location",
                     size_max=50)

# Save the plot as an HTML file
fig.write_html('covid_total_cases_plot.html')

In [ ]:
# Continent vs Total Case as a Pie Chart
fig = px.pie(
    data,
    names='continent',
    values='total_cases',
    title='Continent-wise Total COVID-19 Cases'
)
fig.update_traces(textposition='inside', textinfo='percent+label')  # Display percentage and label inside the pie slices
fig.show()

In [ ]:
# Continent vs total_vaccinations as a Pie Chart
fig = px.pie(
    data,
    names='continent',
    values='total_vaccinations',
    title='Continent-wise Total COVID-19 Cases'
)
fig.update_traces(textposition='inside', textinfo='percent+label')  # Display percentage and label inside the pie slices
fig.show()

In [ ]:
# World Map vs Total Case
fig = px.choropleth(
    data,
    locations='location',
    locationmode='country names',
    color='total_cases',
    color_continuous_scale='viridis',
    title='Total COVID-19 Cases by Country',
    labels={'total_cases': 'Total Cases'},
)
fig.update_geos(projection_type="natural earth")
fig.show()

In [ ]:
# World vs Total Case + Time
fig = px.scatter(data, x='date', y='total_cases', color='location', title='World-wise Total COVID-19 Cases over Time')
fig.update_xaxes(title_text='Time')
fig.update_yaxes(title_text='Total Cases')
fig.show()

In [ ]:
# World vs Total Vaccinations + Time
fig = px.scatter(data, x='date', y='total_vaccinations', color='location', title='World-wise Total COVID-19 Vaccinations over Time')
fig.update_xaxes(title_text='Time')
fig.update_yaxes(title_text='Total Vaccinations')
fig.show()